fdatabase.lo: /home/work/app/src/php-5.4.41/ext/fdatabase/fdatabase.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/work/app/src/php-5.4.41/ext/fdatabase $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/work/app/src/php-5.4.41/ext/fdatabase/fdatabase.c -o fdatabase.lo 
$(phplibdir)/fdatabase.la: ./fdatabase.la
	$(LIBTOOL) --mode=install cp ./fdatabase.la $(phplibdir)

./fdatabase.la: $(shared_objects_fdatabase) $(FDATABASE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_fdatabase) $(FDATABASE_SHARED_LIBADD)

